# Generated by Django 4.2.6 on 2023-10-23 11:18

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stanowisko',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=60)),
                ('opis', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Osoba',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imie', models.CharField(max_length=60)),
                ('nazwisko', models.CharField(max_length=60)),
                ('plec', models.CharField(choices=[('K', 'Kobieta'), ('M', 'Mezczyzna'), ('I', 'Inna')], max_length=1)),
                ('data_dodania', models.DateField(default=datetime.date.today, editable=False)),
                ('stanowisko', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ludzie.stanowisko')),
            ],
        ),
    ]
