# Generated by Django 4.2.6 on 2023-10-23 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ludzie', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='osoba',
            name='plec',
            field=models.IntegerField(choices=[(1, 'Kobieta'), (2, 'Mezczyzna'), (3, 'Inna')]),
        ),
    ]
