# Generated by Django 4.2.6 on 2023-11-06 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ludzie', '0002_alter_osoba_plec'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='osoba',
            options={'ordering': ['-nazwisko'], 'verbose_name_plural': 'osoby'},
        ),
        migrations.AddField(
            model_name='osoba',
            name='miesiac_dodania',
            field=models.CharField(default='November', editable=False, max_length=213),
        ),
    ]
