# Generated by Django 4.2.6 on 2023-11-06 12:19

from django.db import migrations, models
import ludzie.validators


class Migration(migrations.Migration):

    dependencies = [
        ('ludzie', '0003_alter_osoba_options_osoba_miesiac_dodania'),
    ]

    operations = [
        migrations.AlterField(
            model_name='osoba',
            name='imie',
            field=models.CharField(max_length=60, validators=[ludzie.validators.czy_literki]),
        ),
        migrations.AlterField(
            model_name='osoba',
            name='miesiac_dodania',
            field=models.CharField(default='November', max_length=213, validators=[ludzie.validators.czy_nie_przyszlosc_miesiac]),
        ),
    ]
