# Generated by Django 4.2.6 on 2023-11-20 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ludzie', '0005_osoba_wlasciciel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='osoba',
            options={'ordering': ['-nazwisko'], 'permissions': [('can_view_other_persons', 'Sees everyon'), ('close_task', 'Can remove a task by setting its status as closed')], 'verbose_name_plural': 'osoby'},
        ),
    ]
