# Generated by Django 4.2.6 on 2023-10-16 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poolingExercise', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='symbol',
            field=models.CharField(max_length=365, null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='name',
            field=models.CharField(max_length=60, null=True),
        ),
    ]
